/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

import java.util.ArrayList;

/**
 *
 * @author juanf
 */
public class Main extends javax.swing.JFrame {
//////////////////////////////////////////////////////////////////////
    
   public ArrayList<juego> l1(juego ju){
       
       int contador=0;
       
       ArrayList<juego> list = new ArrayList<juego>();
       
       char [][]p ={{'0','0','0'}, {'0', '0', '0'}, {'0','0','0',}} ;
       
         for(int i=0;i<3; i++){//filas
            for(int k=0; k<3;k++){//columnas
                 p[i][k]='X';
                ju.setM(p);
                list.add(contador, ju);
                contador++;
                imprimir(p);
                p[i][k]='0';
           } 
         }
           
       return list;
   }
   
   public static void imprimir(char [][] prueba){
        char p[]={' ',' ',' '};
        String f = "|";
        int  j=0,k=0;
             for(j=0;j<3;++j){
                  for(k=0;k<3;++k){
                      char y=prueba[j][k];
                      f+=y;
                      p[k]=y;    
                   }
                 System.out.println(f);
                 f="|";
            }
        System.out.println("\n");
   }
////////////////////////////////////////////////////////////////////////// 
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setBackground(new java.awt.Color(255, 51, 51));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        juego a= new juego(1);
        ArrayList<juego> p= l1(a);
        
    }//GEN-LAST:event_b1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    // End of variables declaration//GEN-END:variables
}
